DROP TABLE IF EXISTS TB_PESSOAS ;
CREATE TABLE TB_PESSOAS (
    ID_PESSOA INTEGER PRIMARY KEY AUTOINCREMENT,   
    NOME_PESSOA TEXT NOT NULL,
    ID_AREA_INTERESSE INTEGER ,
    TEL_PESSOA INTEGER NOT NULL,
    DT_HR_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS TB_AREAS;
CREATE TABLE TB_AREAS(
    ID_AREA INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME_AREA TEXT NOT NULL,
    STATUS_AREA boolean NOT NULL,
    DTHR_ULTIMA_ATUALIZACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);